theme: jekyll-theme-minimal
title: Victor Hsu
description: Personal website of Victor Hsu
author_name: Victor Hsu
author_title: PhD Student
author_department: Department of Government
author_university: The University of Texas at Austin
author_photo: /profile.jpg
