theme: jekyll-theme-minimal
title: Victor Hsu

description: |
  PhD Student
  <br>
  Department of Government
  <br>
  The University of Texas at Austin
  <br>
  <a href="mailto:vic.hsu@utexas.edu">vic.hsu@utexas.edu</a>

author_name: Victor Hsu
author_title: PhD Student
author_department: Department of Government
author_university: The University of Texas at Austin

logo: /profile.jpg
